version: '3.4'
services:
  weaviate:
    image: semitechnologies/weaviate:1.18.2
    restart: on-failure:0
    volumes:
      - /var/weaviate:/var/lib/weaviate
    ports:
     - "8080:8080"
    environment:
      QUERY_DEFAULTS_LIMIT: 20
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate/data"
      DEFAULT_VECTORIZER_MODULE: text2vec-openai
      ENABLE_MODULES: text2vec-openai
      OPENAI_APIKEY: <OPENAI_API_KEY>
      CLUSTER_HOSTNAME: 'node1'
  max:
    build: .
    environment:
      SLACK_BOT_TOKEN: <SLACK_BOT_TOKEN>
      SLACK_SIGNING_SECRET: <SLACK_SIGNING_SECRET>
      OPENAI_TOKEN: <OPENAI_TOKEN>
      POSTHOG_API_KEY: <POSTHOG_API_KEY>
      POSTHOG_HOST: app.posthog.com
      PD_API_KEY: <PD_API_KEY>
      WEAVIATE_HOST: <WEAVIATE_HOST>
      WEAVIATE_PORT: <WEAVIATE_PORT>
    ports:
      - "8000:8000"