version: '3.4'
services:
  weaviate:
    image: semitechnologies/weaviate:1.18.2
    restart: on-failure:0
    volumes:
      - /var/weaviate:/var/lib/weaviate
    ports:
     - "8080:8080"
    environment:
      QUERY_DEFAULTS_LIMIT: 20
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: "./data"
      DEFAULT_VECTORIZER_MODULE: text2vec-openai
      ENABLE_MODULES: text2vec-openai
      OPENAI_APIKEY: <OPENAI_API_KEY>
      CLUSTER_HOSTNAME: 'node1'
  max:
    build: .
    ports:
      - "8000:8000"